spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    com.ohgiraffers.dalryeo: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: "OFF"
    org.hibernate.orm.jdbc.bind: "OFF"
    org.hibernate.type.descriptor.sql.BasicBinder: "OFF"
