CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	status varchar(20) DEFAULT 'NORMAL'::character varying NOT NULL,
	nickname varchar(30) NULL,
	gender varchar(1) NULL,
	birth date NULL,
	height int4 NULL,
	weight int4 NULL,
	profile_image varchar(500) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_at timestamp NULL,
	CONSTRAINT chk_users_gender CHECK (((gender IS NULL) OR ((gender)::text = ANY ((ARRAY['F'::character varying, 'M'::character varying, 'O'::character varying])::text[])))),
	CONSTRAINT chk_users_status CHECK (((status)::text = ANY ((ARRAY['NORMAL'::character varying, 'BANNED'::character varying, 'WITHDRAWN'::character varying])::text[]))),
	CONSTRAINT users_nickname_key UNIQUE (nickname),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tier (
	tier_code varchar(50) NOT NULL,
	display_name varchar(50) NOT NULL,
	min_score float8 NOT NULL,
	max_score float8 NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	default_profile_image varchar(500) NOT NULL,
	CONSTRAINT tier_pkey PRIMARY KEY (tier_code)
);

CREATE TABLE public.tier_grade (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tier_code varchar(50) NOT NULL,
	grade varchar(1) NOT NULL,
	min_score float8 NOT NULL,
	max_score float8 NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chk_tier_grade_grade CHECK (((grade)::text = ANY ((ARRAY['G'::character varying, 'S'::character varying, 'B'::character varying])::text[]))),
	CONSTRAINT tier_grade_pkey PRIMARY KEY (id),
	CONSTRAINT uq_tier_grade_tier_grade UNIQUE (tier_code, grade),
	CONSTRAINT fk_tier_grade_tier FOREIGN KEY (tier_code) REFERENCES public.tier(tier_code) ON DELETE CASCADE
);

CREATE TABLE public.oauth_client (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	provider varchar(20) NOT NULL,
	provider_id varchar(150) NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chk_oauth_provider CHECK (((provider)::text = ANY ((ARRAY['APPLE'::character varying, 'GOOGLE'::character varying])::text[]))),
	CONSTRAINT oauth_client_pkey PRIMARY KEY (id),
	CONSTRAINT uq_oauth_provider UNIQUE (provider, provider_id),
	CONSTRAINT uq_oauth_user_provider UNIQUE (user_id, provider),
	CONSTRAINT fk_oauth_client_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.auth_tokens (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	refresh_token_hash varchar(255) NOT NULL,
	expires_at timestamp NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	revoked_at timestamp NULL,
	CONSTRAINT auth_tokens_pkey PRIMARY KEY (id),
	CONSTRAINT uq_auth_tokens_hash UNIQUE (refresh_token_hash),
	CONSTRAINT uq_auth_tokens_user UNIQUE (user_id),
	CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.running_records (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	"source" varchar(20) NOT NULL,
	distance_km float8 NOT NULL,
	duration_sec int4 NOT NULL,
	avg_pace_sec_per_km int4 NOT NULL,
	avg_heart_rate int4 NULL,
	calories_kcal int4 NULL,
	start_at timestamp NOT NULL,
	end_at timestamp NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chk_running_records_distance CHECK ((distance_km > (0)::double precision)),
	CONSTRAINT chk_running_records_duration CHECK ((duration_sec > 0)),
	CONSTRAINT chk_running_records_pace CHECK ((avg_pace_sec_per_km > 0)),
		CONSTRAINT chk_running_records_source CHECK (((source)::text = ANY ((ARRAY['IOS'::character varying, 'ANDROID'::character varying, 'APPLE_WATCH'::character varying, 'GALAXY_WATCH'::character varying])::text[]))),
	CONSTRAINT chk_running_records_time CHECK ((end_at >= start_at)),
	CONSTRAINT running_records_pkey PRIMARY KEY (id),
	CONSTRAINT fk_running_records_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);
CREATE INDEX idx_running_records_start_at ON public.running_records USING btree (start_at DESC);
CREATE INDEX idx_running_records_user_start_at ON public.running_records USING btree (user_id, start_at DESC);

CREATE TABLE public.weekly_tiers (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	week_start_date date NOT NULL,
	tier_code varchar(50) NOT NULL,
	tier_score int4 NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT uq_user_week UNIQUE (user_id, week_start_date),
	CONSTRAINT weekly_tiers_pkey PRIMARY KEY (id),
	CONSTRAINT fk_weekly_tiers_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);
CREATE INDEX idx_weekly_tiers_user_week ON public.weekly_tiers USING btree (user_id, week_start_date DESC);

CREATE TABLE public.weekly_user_stats (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	week_start_date date NOT NULL,
	run_count int4 DEFAULT 0 NOT NULL,
	total_distance_km numeric(10, 3) DEFAULT 0 NOT NULL,
	total_duration_sec int4 DEFAULT 0 NOT NULL,
	weighted_pace_sum numeric(14, 3) DEFAULT 0 NOT NULL,
	avg_pace_sec_per_km int4 DEFAULT 0 NOT NULL,
	tier_score_sum numeric(10, 2) DEFAULT 0 NOT NULL,
	tier_score numeric(5, 2) DEFAULT 0 NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT uq_weekly_user_stats_user_week UNIQUE (user_id, week_start_date),
	CONSTRAINT weekly_user_stats_pkey PRIMARY KEY (id),
	CONSTRAINT fk_weekly_user_stats_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);
CREATE INDEX idx_weekly_user_stats_distance_ranking ON public.weekly_user_stats USING btree (week_start_date, total_distance_km DESC, tier_score DESC, user_id);
CREATE INDEX idx_weekly_user_stats_score_ranking ON public.weekly_user_stats USING btree (week_start_date, tier_score DESC, total_distance_km DESC, user_id);

CREATE TABLE public.record_outbox_events (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	event_type varchar(50) NOT NULL,
	aggregate_id int8 NOT NULL,
	status varchar(20) DEFAULT 'PENDING'::character varying NOT NULL,
	retry_count int4 DEFAULT 0 NOT NULL,
	next_retry_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_error varchar(1000) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chk_record_outbox_events_retry_count CHECK ((retry_count >= 0)),
	CONSTRAINT chk_record_outbox_events_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'DONE'::character varying, 'FAILED'::character varying])::text[]))),
	CONSTRAINT chk_record_outbox_events_type CHECK (((event_type)::text = 'WEEKLY_STATS_UPDATE_REQUESTED'::text)),
	CONSTRAINT record_outbox_events_pkey PRIMARY KEY (id),
	CONSTRAINT uq_record_outbox_events_type_aggregate UNIQUE (event_type, aggregate_id),
	CONSTRAINT fk_record_outbox_events_running_record FOREIGN KEY (aggregate_id) REFERENCES public.running_records(id) ON DELETE CASCADE
);
CREATE INDEX idx_record_outbox_events_pending_retry ON public.record_outbox_events USING btree (next_retry_at, id) WHERE ((status)::text = 'PENDING'::text);
CREATE INDEX idx_record_outbox_events_status_retry ON public.record_outbox_events USING btree (status, next_retry_at, id);

INSERT INTO public.tier (tier_code, display_name, min_score, max_score, default_profile_image)
VALUES
    ('CHEETAH', '치타', 1.50, 999.99, '/profiles/tiers/cheetah.png'),
    ('DEER', '사슴', 1.20, 1.49, '/profiles/tiers/deer.png'),
    ('HUSKY', '허스키', 1.00, 1.19, '/profiles/tiers/husky.png'),
    ('FOX', '여우', 0.86, 0.99, '/profiles/tiers/fox.png'),
    ('WATERDEER', '고라니', 0.75, 0.85, '/profiles/tiers/waterdeer.png'),
    ('SHEEP', '양', 0.67, 0.74, '/profiles/tiers/sheep.png'),
    ('RABBIT', '토끼', 0.60, 0.66, '/profiles/tiers/rabbit.png'),
    ('PANDA', '판다', 0.55, 0.59, '/profiles/tiers/panda.png'),
    ('DUCK', '오리', 0.46, 0.54, '/profiles/tiers/duck.png'),
    ('TURTLE', '거북이', 0.00, 0.45, '/profiles/tiers/turtle.png')
ON CONFLICT (tier_code) DO UPDATE
SET display_name = EXCLUDED.display_name,
    min_score = EXCLUDED.min_score,
    max_score = EXCLUDED.max_score,
    default_profile_image = EXCLUDED.default_profile_image;

INSERT INTO public.tier_grade (tier_code, grade, min_score, max_score)
VALUES
    ('CHEETAH', 'G', 1.64, 999.99),
    ('CHEETAH', 'S', 1.57, 1.63),
    ('CHEETAH', 'B', 1.50, 1.56),
    ('DEER', 'G', 1.39, 1.49),
    ('DEER', 'S', 1.29, 1.38),
    ('DEER', 'B', 1.20, 1.28),
    ('HUSKY', 'G', 1.13, 1.19),
    ('HUSKY', 'S', 1.06, 1.12),
    ('HUSKY', 'B', 1.00, 1.05),
    ('FOX', 'G', 0.95, 0.99),
    ('FOX', 'S', 0.90, 0.94),
    ('FOX', 'B', 0.86, 0.89),
    ('WATERDEER', 'G', 0.82, 0.85),
    ('WATERDEER', 'S', 0.78, 0.81),
    ('WATERDEER', 'B', 0.75, 0.77),
    ('SHEEP', 'G', 0.72, 0.74),
    ('SHEEP', 'S', 0.69, 0.71),
    ('SHEEP', 'B', 0.67, 0.68),
    ('RABBIT', 'G', 0.64, 0.66),
    ('RABBIT', 'S', 0.62, 0.63),
    ('RABBIT', 'B', 0.60, 0.61),
    ('PANDA', 'G', 0.58, 0.59),
    ('PANDA', 'S', 0.56, 0.57),
    ('PANDA', 'B', 0.55, 0.55),
    ('DUCK', 'G', 0.52, 0.54),
    ('DUCK', 'S', 0.49, 0.51),
    ('DUCK', 'B', 0.46, 0.48)
ON CONFLICT (tier_code, grade) DO UPDATE
SET min_score = EXCLUDED.min_score,
    max_score = EXCLUDED.max_score;
